/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.svendsen.structures;

public class App {

    public static void main(String[] args) {

        List<Integer> list = new LinkedList<>();
        System.out.println(list.isEmpty());
        System.out.println(list.size());
        
        list.add(10);
        list.add(11);
        list.add(69);

        System.out.println(list.isEmpty());
        System.out.println(list.size());
        System.out.println(list.get(0));
        System.out.println(list.get(1));
        System.out.println(list.get(2));
        
        System.out.println("NEW TEST:");

        list.add(2, 420);
        System.out.println(list.get(0));
        System.out.println(list.get(1));
        System.out.println(list.get(2));
        System.out.println(list.get(3));
        System.out.println(list);

        
    }
}
